name: 15 - Working with Matrices

on:
  workflow_dispatch:

jobs:

  include-example:
  
    runs-on: ubuntu-latest
    name: ${{ matrix.color }}-${{ matrix.shape }}-${{ matrix.value }}
    strategy:
    
      matrix:
        
        color: [red,green]
        shape: [circle,square]
        size: [small, large]
        
        include:
        
        - color: red
          opacity: 75
        - shape: triangle
          opacity: 100
        - color: red
          shape: triangle
        - opacity: 50

    steps:
      - name: Dummy step
        run: echo "${{ matrix.opacity }}-${{ matrix.color }}-${{ matrix.shape }}-${{ matrix.size }}"
    
          

  backwards-compatibility:
    strategy:
      matrix:
        java-version: [11, 17, 21]
        os: 
          - ubuntu-latest
          - windows-latest
        include:
          - os: ubuntu-latest
            java-version: 21
            tag: experimental
          - os: ubuntu-latest
            java-version: 17
      fail-fast: false 

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '${{ matrix.java-version }}'
          cache: 'maven'
          cache-dependency-path: 'pom.xml' 

      - name: Fail if experimental
        if: ${{ matrix.tag == 'experimental' }}
        run: exit 1

      - name: Print environment
        run: |
          echo "Running on OS ${{ matrix.os }} with Java version ${{ matrix.java-version }}"
          sleep 10


    
