name: 15 - Working with Matrices

on:
  workflow_dispatch:

jobs:
  backwards-compatibility:
    strategy:
      matrix:
        java-version: [11, 17, 21]
        os: 
          - ubuntu-latest
          - windows-latest
      fail-fast: false # Optional: continue running other jobs if one fails

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '${{ matrix.java-version }}'
          cache: 'maven'
          cache-dependency-path: 'pom.xml' 

      - name: Print environment
        run: echo "Running on OS ${{ matrix.os }} with Java version ${{ matrix.java-version }}"
