
name: 02 - Workflow Events

on:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  schedule:
    - cron: '* * * * *'

 
  workflow_dispatch:


jobs:

  echo_trigger:

    runs-on: ubuntu-latest
    steps:
      - name: show the trigger
        run: "I will show the trigger"
        
  echo_event:
    runs_on: ubuntu-latest
    steps:
      - name: show the event
        run: echo "Event name: ${{ github.event_name }}"
      
