# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: 06 - Contexts.

run-name: My custom workflow run - ${{ github.actor }} triggered a ${{ github.event_name }} event

on:
  push:
    branches: [ "main" ]
    
  workflow_dispatch:
      

jobs:

  echo-data:

    runs-on: ubuntu-latest

    steps:
    
    - name: Display informantion
      run: |
        echo "Event name= ${{ github.event_name }}"
        echo "Ref= ${{ github.ref }}"
        echo "SHA= ${{ github.sha }}"
        echo "Actor= ${{ github.actor }}"
        echo "Workflow= ${{ github.workflow }}"
        echo "Run ID= ${{ github.run_id }}"
        echo "Run number= ${{ github.run_number }}"
        echo "Run my var ${{ secrets.MY_VAR}}"
        

