name:  09 - Organization, Repository, and Environment Variables

on:
  push:
    branches: [ "main" ]
    
  workflow_dispatch:

env:
  OVERWRITTEN: 'I am a workflow env var'
  UNDEFINED_VAR_WITH_DEFAULT: ${{ vars.UNDEFINED_VAR || 'default value' }}
  
    

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print Environment Variables
        run: |
          echo "ORG_VAR: ${{ secrets.ORG_VAR }}"
          echo "OVERWRITTEN_VAR: ${{ secrets.OVERWRITTEN_VAR }}"
          echo "Repo var: ${{ secrets.REPOSITORY_VAR }}"
          echo "Environment var: ${{ vars.TARGET_VAR }}"
          

  echo2:
    runs-on: ubuntu-latest

    steps:
      - name: Print repostory env
        run: |
          echo "Repo var: ${{ secrets.REPOSITORY_VAR }}"

  echo-undefined:
    runs-on: ubuntu-latest
    steps:
      - name: Print Undefined Variables
        run: |
          echo "Org var: ${{ env.UNDEFINED_VAR_WITH_DEFAULT }}"
          
  
