name:  09 - Organization, Repository, and Environment Variables

on:
  push:
    branches: [ "main" ]
    
  workflow_dispatch:
    

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print Environment Variables
        run: |
          echo "ORG_VAR: ${{ secrets.ORG_VAR }}"
          echo "OVERWRITTEN_VAR: ${{ secrets.OVERWRITTEN_VAR }}"
