name: 12 - Working with Outputs

on:
  workflow_dispatch:
    inputs:
      build-status:
        description: "Status of the build"
        type: choice
        options:
          - success
          - failure
        default: success

jobs:
  build1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.build1.outputs.output1 }}
    steps:
      - name: Build Step 1
        id: build1
        run: |
          echo "output1=value1" >> "$GITHUB_OUTPUT"
          echo "output2=value2" >> "$GITHUB_OUTPUT"
          cat "$GITHUB_OUTPUT"
          
      - name: Step with mistake
        run: |
          echo "mistake=true" > "$GITHUB_OUTPUT"  # Use '>' to overwrite intentionally
          cat "$GITHUB_OUTPUT"
          
  build:
    runs-on: ubuntu-latest
    outputs:
      build-status: ${{ steps.build.outputs.status }}
    steps:
      - name: Print GITHUB_OUTPUT path
        run: echo "GITHUB_OUTPUT is at $GITHUB_OUTPUT"

      - name: Build
        id: build
        run: |
          echo "status=${{ inputs.build-status }}" >> "$GITHUB_OUTPUT"
          
  deploy: 
    runs-on: ubuntu-latest
    needs:
      - build
      - build1
    if: ${{ inputs.build-status == 'success' }}
    steps:
      - name: Deploy
        run: |
          echo "Deploying"
          echo "Output from build job: ${{ needs.build1.outputs.output1 }}"
