name: 13 - Using Caching

on:
  workflow_dispatch:
    inputs:
      use-cache:
        description: "Whether to execute cache step"
        type: boolean
        default: true

      maven-version:
        description: "Maven version"
        type: choice
        options:
          - 3.6.3
          - 3.8.6
          - 3.9.9
        default: 3.9.9

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code 
      uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Maven
      uses: actions/setup-java@v4
      with:
        maven-version: ${{ inputs.maven-version }}

    - name: Downloading Cached Dependencies
      id: cache
      if: ${{ inputs.use-cache }}
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}

    - name: Install dependencies
      run: mvn install
      if: ${{ steps.cache.outputs.cache-hit != 'true' }}

    - name: Testing
      run: mvn test

    - name: Building
      run: mvn package

    - name: Deploying to nonprod
      run: echo "Deploying to nonprod"
