name: 14 - Working with Artifacts

on:
  workflow_dispatch:
    inputs:
      maven-version:
        description: "Maven version"
        type: choice
        options:
          - 4.0.0
          - 3.9.9
          - 3.6.3
        default: 3.9.9

env:
  build-artifact-key: app-${{ github.sha }}
  test-coverage-key: test-coverage-${{ github.sha }}

jobs:

  install-deps:
    runs-on: ubuntu-latest
    
    outputs:
      deps-cache-key: ${{ steps.cache-key.outputs.cache_key }}
    
    steps:
      - name: Checkout code 
        uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
          cache-dependency-path: 'pom.xml' 
      
      - name: Calculate cached dependencies key
        id: cache-key
        run: |
          echo "cache_key=deps-maven-${{ hashFiles('pom.xml') }}" >> $GITHUB_ENV

      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
            
      - name: Install dependencies
        run: mvn clean install
        if: steps.cache-key.outputs.cache-hit != 'true'


  build:
    runs-on: ubuntu-latest
    needs: install-deps

    steps:
      - name: Checkout code 
        uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
          cache-dependency-path: 'pom.xml' 
          
       
      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
         path: ~/.m2/repository
         key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
  
         restore-keys: |
           ${{ runner.os }}-maven-
            
      - name: Testing
        run: mvn test jacoco:report

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.test-coverage-key }}
          path: target/site/jacoco/

      - name: Building
        run: mvn package

      - name: Upload build files
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.build-artifact-key }}
          path: target/*.jar 


  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build files
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.build-artifact-key }}
          path: build

      - name: Deploy to production
        run: echo "Deploying the application to production"
