
name: 14 - Working with Artifacts

on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  workflow_dispatch:
    

jobs:

  setup-java:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 
        uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
          cache-dependency-path: 'pom.xml' 
          
  install-deps:
    runs-on: ubuntu-latest
    needs:
      - setup-java
      
    outputs:
      deps-cache-key: ${{ steps.cache-key.outputs.CACHE_KEY }}
    
    steps:

      - name: Calculate cached dependencies key
        id: cache-key
        run: |
          echo "CACHE_KEY=deps-maven-${{ hashFiles('pom.xml') }}" >> $GITHUB_ENV
        env:
          CACHE_KEY: deps-maven-${{ hashFiles('pom.xml') }}

      - name: Download cached dependencies
        uses: actions/cache@v3
        id: cache
        with:
          path: ~/.m2/repository
          key: ${{ env.CACHE_KEY }}

      - name: Install dependencies
        run: mvn clean install
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}


  build:
    runs-on: ubuntu-latest
    needs:
      - setup-java
      - install-deps  

    steps:

      - name: Download cached dependencies using install-deps job's cache key
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ needs.install-deps.outputs.deps-cache-key }}


      - name: Testing
        run: mvn test

      - name: Building
        run: mvn package

      - name: Upload build files
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: 14-artifacts/react-app/build

  deploy:
    runs-on: ubuntu-latest
    needs: 
      - build
    steps:
      - name: Download build files
        uses: actions/donwload-artifact@v4
        with:
          name: app
          path: build

      - name: Deploy to production
        run: echo "Deploying the application to production"
