
name: 15 - Working with Matrices

on:
  workflow_dispatch:
    

jobs:

  backwards-compatibility:
    strategy:
      matrix:
        name: ${{ matrix.os }}-${{ matrix.java-version }}
        java-version: [11,17,21]
        os:
          - ubuntu-latest
          - windows-latest
          
        include:
          - os: ubuntu-latest
            tag: linux
            
          - os: ubuntu-latest
            java-version: 21
          

    runs-on: ubuntu-latest

  
