name: 16 - Working with Environments
run-name: 16 - Working with Environments | env - {{ inputs.target-env }}
on:
  workflow_dispatch:
    inputs:
      target-env:
        type: environment
        default: staging
      
      

jobs:
  build:
  
    runs-on: ubuntu-latest
    environment: prod
    env: 
      my-env-value: MY_ENV_VALUE
      
    steps:

      - name: Echo vars
        run:  |
          echo "Env variable - ${{ env.my-env-value }}"
      
    
    
