

name: 19 - 1 - Managing Concurrency
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
    
on:
  workflow_dispatch:
    
jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Ping URL
      run: |
        url="http://invalid-url.com"   # URL to check
        max_trials=20                  # Maximum number of trials
        delay=5                        # Delay between trials (seconds)

        echo "Pinging $url with $max_trials trials and $delay seconds delay."

        for ((i=1; i<=max_trials; i++)); do
          # Use curl to check if the URL is reachable
          if curl --head --silent --fail "$url"; then
            echo "URL is reachable on trial $i!"
            break
          else
            echo "Trial $i: URL is not reachable. Retrying in $delay seconds..."
            sleep $delay
          fi
        done

        if [[ $i -gt $max_trials ]]; then
          echo "Max trials reached. URL is still not reachable."
          exit 1  
      

